### ISSUE TITLE
关于微信小程序“复制到剪贴板”功能无法正常使用

### ISSUE THREAD

**Issue by sxf666** [SierraQin/metro.mp#1]
在您的小程序“列车运行前方”内
点击 项目说明-前往项目主页-复制到剪贴板-复制的内容为您的老项目主页“https://gitee.com/SierraQin/metro”
实际上应当复制的内容为“https://github.com/SierraQin/metro”（虽然显示的如此）

**Comment by SierraQin** [comment]
感谢您的反馈！问题已定位，并将于近期修复，预计随下个版本发布
小程序相关问题您可移步 [https://github.com/SierraQin/metro.mp](https://github.com/SierraQin/metro.mp)

**Comment by SierraQin** [comment]
问题已修复，相关版本已提交公众平台审核发布。
相关提交： [https://github.com/SierraQin/metro.mp/commit/359c81233b09fde2283f38ed4ec07cf1d6593957](https://github.com/SierraQin/metro.mp/commit/359c81233b09fde2283f38ed4ec07cf1d6593957)
再次感谢您的反馈！
